version: "3"

services:

  runtime-setup:
    image: swift-asn1:22.04-6.0
    build:
      args:
        base_image: "swiftlang/swift:nightly-6.0-jammy"

  test:
    image: swift-asn1:22.04-6.0
    environment:
      - SWIFT_VERSION=6.0
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - EXPLICIT_SENDABLE_ARG=-Xswiftc -require-explicit-sendable
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-asn1:22.04-6.0

  update-benchmark-baseline:
    image: swift-asn1:22.04-6.0
    environment:
      - SWIFT_VERSION=6.0
