name: PR

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    soundness:
        name: Soundness
        uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
        with:
            api_breakage_check_enabled: true
            broken_symlink_check_enabled: true
            docs_check_enabled: true
            format_check_enabled: true
            license_header_check_enabled: true
            license_header_check_project_name: "SwiftASN1"
            shell_check_enabled: true
            unacceptable_language_check_enabled: true
    unit-tests:
        name: Unit tests
        uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
        with:
            linux_5_9_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
            linux_5_10_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
            linux_nightly_6_0_arguments_override: "--explicit-target-dependency-import-check error"
            linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

    benchmarks:
        name: Benchmarks
        uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
        with:
            benchmark_package_path: "Benchmarks"

    cxx-interop:
        name: Cxx interop
        uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main

    swift-6-language-mode:
        name: Swift 6 Language Mode
        uses: apple/swift-nio/.github/workflows/swift_6_language_mode.yml@main
        if: false  # Disabled for now.
